name: Run tests

on:
  - push
  - pull_request

jobs:

  ubuntu-ppa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ppa-version:
          # the ppa is currently on 0.7.2 but we need >=0.9
          #- stable
          - unstable
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/${{ matrix.ppa-version }}
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends neovim scdoc lua-busted
    - name: Run the test suite
      run: make test BUSTED='busted --exclude-tags=ppa,v10'
      env:
        TERM: dumb

  appimage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v0.10.0, v0.10.1, v0.10.2, v0.10.3, v0.10.4, nightly]
        tags:
          - [appimage, v10]
        include:
          - version: v0.9.0
            tags: [appimage]
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends scdoc lua-busted
    - name: Download official neovim appimage
      run: |
        wget https://github.com/neovim/neovim/releases/download/${{ matrix.version }}/nvim.appimage{,.sha256sum}
        sha256sum -c nvim.appimage.sha256sum
        chmod +x nvim.appimage
        ./nvim.appimage --appimage-extract
    - name: Run the test suite
      run: make test "BUSTED=busted --exclude-tags=${{ join(matrix.tags, ',') }}"
      env:
        TERM: dumb
        NVIMPAGER_NVIM: squashfs-root/usr/bin/nvim


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        brew update
        brew install neovim scdoc luarocks
        luarocks --local install busted
    - name: Run the test suite
      run: make test BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=mac,v10"
      env:
        TERM: dumb

  macos-nix:
    runs-on: macos-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
    - uses: actions/checkout@v3
    - name: Run the test suite via nix
      run: nix build --print-build-logs

  nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - default
          - nightly
        update:
          - false
          - true
        exclude:
          - package: nightly
            update: false
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v20
    - uses: cachix/cachix-action@v12
      with:
        name: nix-community
    - uses: actions/checkout@v3
    - name: Update the fake inputs
      run: nix flake update
      if: matrix.update
    - name: Run the test suite with ${{ matrix.package }} neovim
      run: nix build --print-build-logs '.#${{ matrix.package }}'
